name: deploy

on:
  push:
    branches:
       - "master"
  pull_request:
    branches:
      - "master"

jobs:
  prettier:
    runs-on: ubuntu-20.04
    container:
      image: node:14.17-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Check our source code by prettier
        continue-on-error: true
        run: npx prettier --check "**/**.js" --single-quote
  typescript:
    runs-on: ubuntu-20.04
    container:
      image: node:14.17-alpine
    steps:
      - name: TypeScript check
        run: npx tsc 