name: deploy

on:
  push:
    branches:
       - "master"
  pull_request:
    branches:
      - "master"

jobs:
  prettier:
    runs-on: ubuntu-20.04
    container:
      image: node:14.17-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install Prettier
        run: npm i prettier
      - name: Prettify our source code with Prettier
        run: npx prettier --check --single-quote